# Seed for randomness, remove field for non-deterministic results
seed = 1

[camera]
use_dof = false
# APS-C Canon
sensor_width = 22.3
sensor_height = 14.9

[camera.lens]
clip_start = 0.1
clip_end = 1000
focal_length = 50

[camera.dof]
aperture_fstop    = 2.8

[camera.location]
mode = "random"

[camera.location.random]
r_min   = 8
r_max   = 8
inc_min = 'math.pi / 4'
inc_max = 'math.pi / 2'
azi_min = 0.0
azi_max = '2 * math.pi'

[camera.location.uniform]
radius = 1
inc_start = 'math.nextafter(math.pi / 2, -math.inf)'
inc_stop = 'math.pi / 2'
inc_step = 'math.pi / 2'

[world]
strength = 1.0
# color = "environment_texture"
# color = "image_texture"

[world.environment_texture]
path = ""

[world.image_texture]
path = ""
extension = 'EXTEND'

[light]
mode = 'uniform'
type = 'SUN'
energy = 1.0

[light.uniform]
amount = 3
radius = 10
inc_start = 'math.pi / 4'
inc_stop = 'math.pi / 2'
inc_step = 'math.pi / 2'

[render]
resolution_x = 200
resolution_y = 200
engine = "cycles"
samples = 256

[render.cycles]
use_denoising = true
use_adaptive_sampling  = true
max_bounces = 1024
diffuse_bounces = 1024
glossy_bounces = 1024
transmission_bounces = 1024
volume_bounces = 1024
transparent_max_bounces = 1024

[render.eevee]
use_raytracing = false
use_gtao = false
use_ssr = false
# Increase shadow pool size to avoid Shadow buffer full error
shadow_pool_size = '1024'
