# Seed for randomness, remove field for non-deterministic results
seed = 1

[camera]
use_dof = false
# APS-C Canon
sensor_width = 22.3
sensor_height = 14.9

[camera.lens]
clip_start = 0.1
clip_end = 1000
focal_length = 50

[camera.dof]
aperture_fstop    = 2.8

[camera.location]
mode = "random"

[camera.location.random]
# Radius range (from origin)
r_min   = 1
r_max   = 1
# Inclination θ ∈ [0, π/2]
inc_min = 0.0
inc_max = 1.5707963267948966
# Azimuth φ ∈ [0, 2π]
azi_min = 0.0
azi_max = 6.283185307179586

[camera.location.uniform]
radius = 1
slices = 5

[light]
energy   = 4.0
radius = 10

[world]
strength = 1.0

[world.environment_texture]
path = ""

[world.image_texture]
path = ""

[render]
resolution_x = 200
resolution_y = 200
engine = "cycles"
samples = 256

[render.cycles]
use_denoising = false
use_adaptive_sampling  = false
max_bounces = 12
diffuse_bounces = 4
glossy_bounces = 4
transmission_bounces = 12
volume_bounces = 0
transparent_max_bounces = 12

[render.eevee]
use_raytracing = false
use_gtao = false
use_ssr = false
# Increase shadow pool size to avoid Shadow buffer full error
shadow_pool_size = '1024'
